import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;
import 'package:shared_preferences/shared_preferences.dart';

import '../../features/journey_planner/domain/models/journey.dart';
import '../../features/station/domain/models/station.dart';
import '../../features/train/domain/models/train.dart';

/// Reads the curated Pakistan Railways dataset bundled in
/// `assets/data/pakrail.json` (generated by `tool/import_pakrail.dart` from
/// public sources — no backend involved).
class PakRailRepository {
  PakRailRepository({this.assetPath = 'assets/data/pakrail.json'});

  final String assetPath;

  /// SharedPreferences key holding a dataset refreshed in the background by
  /// [DatasetRefresher]. When present it takes precedence over the bundled
  /// asset; the bundled asset is always the offline fallback.
  static const String refreshedDatasetPrefsKey = 'pakrail_refreshed_json';

  /// Parsed datasets shared across repository instances so the JSON is loaded
  /// and decoded exactly once per app run.
  static final Map<String, Map<String, dynamic>> _caches = {};

  /// Drops all parsed datasets so the next load re-reads (used after a
  /// background refresh lands).
  static void invalidateCache() => _caches.clear();

  Future<Map<String, dynamic>> _load() async {
    final cached = _caches[assetPath];
    if (cached != null) return cached;
    final parsed = jsonDecode(await _readDataset()) as Map<String, dynamic>;
    _caches[assetPath] = parsed;
    return parsed;
  }

  /// Prefers a refreshed dataset stored by the background refresher; falls
  /// back to the bundled asset so the app always has schedule data offline.
  Future<String> _readDataset() async {
    final refreshed = await _loadRefreshedDataset();
    if (refreshed != null) return refreshed;
    return rootBundle.loadString(assetPath);
  }

  Future<String?> _loadRefreshedDataset() async {
    try {
      final prefs = await SharedPreferences.getInstance().timeout(
        const Duration(milliseconds: 400),
      );
      final raw = prefs.getString(refreshedDatasetPrefsKey);
      if (raw == null || raw.isEmpty) return null;
      // Trust it only if it decodes to a dataset-shaped map.
      final decoded = jsonDecode(raw);
      if (decoded is Map<String, dynamic> &&
          decoded.containsKey('services') &&
          decoded.containsKey('stations')) {
        return raw;
      }
      return null;
    } catch (_) {
      // No preferences available (tests, web edge cases) or corrupt data:
      // the bundled asset remains the source of truth.
      return null;
    }
  }

  /// Dataset metadata (as-of date, timetable season, sources).
  Future<({String dataAsOf, String season, List<String> sources})>
  meta() async {
    final data = await _load();
    final m = data['meta'] as Map<String, dynamic>;
    return (
      dataAsOf: m['dataAsOf'] as String,
      season: m['season'] as String,
      sources: (m['sources'] as List).cast<String>(),
    );
  }

  /// All services as [Train] objects (one entry per UP/DN run).
  Future<List<Train>> loadAllTrains() async {
    final data = await _load();
    final trainsById = _trainsById(data);
    return [
      for (final s in data['services'] as List)
        _toTrain(s as Map<String, dynamic>, trainsById),
    ];
  }

  /// A curated set of well-known services for the Home "Recent Journeys" row.
  Future<List<Train>> popularTrains() async {
    final all = await loadAllTrains();
    const popularIds = ['41UP', '7UP', '5UP']; // Karakoram, Tezgam, Green Line
    final byId = {for (final t in all) t.id: t};
    return [
      for (final id in popularIds)
        if (byId[id] != null) byId[id]!,
    ];
  }

  Future<Train?> trainById(String id) async {
    final all = await loadAllTrains();
    for (final t in all) {
      if (t.id == id) return t;
    }
    return null;
  }

  Future<List<Station>> loadStations() async {
    final data = await _load();
    return [
      for (final s in data['stations'] as List)
        _stationFromJson(s as Map<String, dynamic>),
    ];
  }

  /// Stations whose name or code contains [query] (case-insensitive).
  Future<List<Station>> searchStations(String query) async {
    final all = await loadStations();
    final q = query.trim().toLowerCase();
    if (q.isEmpty) return const [];
    return [
      for (final s in all)
        if (s.name.toLowerCase().contains(q) ||
            s.code.toLowerCase().contains(q))
          s,
    ];
  }

  /// Finds train routes for a query like "Lahore to Karachi" (also accepts
  /// "→" or "->"). Resolves the two endpoints against station names/codes and
  /// returns the journeys running between them.
  Future<List<Journey>> findRoutesForQuery(String query) async {
    final parts = _splitRouteQuery(query);
    if (parts == null) return const [];
    final from = await _resolveStation(parts[0]);
    final to = await _resolveStation(parts[1]);
    if (from == null || to == null || from.id == to.id) return const [];
    return findJourneys(
      fromStationId: from.id,
      toStationId: to.id,
      date: DateTime.now(),
    );
  }

  List<String>? _splitRouteQuery(String query) {
    final q = query.trim();
    if (q.isEmpty) return null;
    for (final sep in const [' → ', ' -> ', ' to ']) {
      final idx = q.toLowerCase().indexOf(sep.toLowerCase());
      if (idx > 0 && idx < q.length - sep.length) {
        return [
          q.substring(0, idx).trim(),
          q.substring(idx + sep.length).trim(),
        ];
      }
    }
    return null;
  }

  /// Resolves a station by exact name/code first, then partial match.
  Future<Station?> _resolveStation(String text) async {
    final q = text.trim().toLowerCase();
    if (q.isEmpty) return null;
    final all = await loadStations();
    Station? partial;
    for (final s in all) {
      if (s.name.toLowerCase() == q || s.code.toLowerCase() == q) {
        return s;
      }
      if (partial == null &&
          (s.name.toLowerCase().contains(q) ||
              s.code.toLowerCase().contains(q))) {
        partial = s;
      }
    }
    return partial;
  }

  Future<Station?> stationById(String id) async {
    final stations = await loadStations();
    for (final s in stations) {
      if (s.id == id) return s;
    }
    return null;
  }

  /// Resolves a station by its display name (used by the route-details sheet,
  /// which only has the stop's name).
  Future<Station?> stationByName(String name) async {
    final stations = await loadStations();
    for (final s in stations) {
      if (s.name.toLowerCase() == name.toLowerCase()) return s;
    }
    return null;
  }

  /// All services that call at [stationId], as [Train] objects.
  Future<List<Train>> trainsThroughStation(String stationId) async {
    final data = await _load();
    final trainsById = _trainsById(data);
    return [
      for (final s in data['services'] as List)
        if (_stopAt((s as Map<String, dynamic>)['stops'] as List, stationId))
          _toTrain(s, trainsById),
    ];
  }

  /// One [Journey] per service (origin → destination): the full route list
  /// shown on the Search page by default. Sorted by departure time.
  Future<List<Journey>> allJourneys({DateTime? date}) async {
    final data = await _load();
    final stationsById = <String, Station>{
      for (final s in data['stations'] as List)
        (s as Map<String, dynamic>)['id'] as String: _stationFromJson(s),
    };
    final trainsById = _trainsById(data);
    final day = date ?? DateTime.now();
    final journeys = <Journey>[];

    for (final s in data['services'] as List) {
      final service = s as Map<String, dynamic>;
      final stops = service['stops'] as List;
      if (stops.isEmpty) continue;
      final first = stops.first as Map<String, dynamic>;
      final last = stops.last as Map<String, dynamic>;
      final from = stationsById[first['stationId']];
      final to = stationsById[last['stationId']];
      if (from == null || to == null) continue;

      journeys.add(
        Journey(
          from: from,
          to: to,
          train: _toTrain(service, trainsById),
          departureTime: _timeOn(
            day,
            first['departureTime'] as String,
            first['dayOffset'] as int,
          ),
          arrivalTime: _timeOn(
            day,
            last['arrivalTime'] as String,
            last['dayOffset'] as int,
          ),
          price: null, // fares are not published in the public timetable
        ),
      );
    }

    journeys.sort((a, b) => a.departureTime.compareTo(b.departureTime));
    return journeys;
  }

  /// Filters the route list for a search query. Accepts "X to Y" (also
  /// "→"/"->") to resolve a specific corridor; otherwise falls back to a
  /// substring match on train name/number or endpoint station names.
  Future<List<Journey>> searchRoutes(String query) async {
    final parts = _splitRouteQuery(query);
    if (parts != null) {
      final from = await _resolveStation(parts[0]);
      final to = await _resolveStation(parts[1]);
      if (from != null && to != null && from.id != to.id) {
        final routes = await findJourneys(
          fromStationId: from.id,
          toStationId: to.id,
          date: DateTime.now(),
        );
        if (routes.isNotEmpty) return routes;
      }
    }

    final all = await allJourneys();
    final q = query.trim().toLowerCase();
    if (q.isEmpty) return all;
    return [
      for (final j in all)
        if (j.train.name.toLowerCase().contains(q) ||
            j.train.number.toLowerCase().contains(q) ||
            j.from.name.toLowerCase().contains(q) ||
            j.to.name.toLowerCase().contains(q))
          j,
    ];
  }

  /// Finds single-train journeys from [fromStationId] to [toStationId] that
  /// depart on the same date as [date].
  ///
  /// All results are direct trains (Pakistan Railways publishes no
  /// connection-building data). Results are sorted by departure time.
  Future<List<Journey>> findJourneys({
    required String fromStationId,
    required String toStationId,
    DateTime? date,
    bool directOnly = false,
  }) async {
    final data = await _load();
    final stationsById = <String, Station>{
      for (final s in data['stations'] as List)
        (s as Map<String, dynamic>)['id'] as String: _stationFromJson(s),
    };
    final trainsById = _trainsById(data);
    final from = stationsById[fromStationId];
    final to = stationsById[toStationId];
    if (from == null || to == null) return const [];

    final day = date ?? DateTime.now();
    final journeys = <Journey>[];

    for (final s in data['services'] as List) {
      final service = s as Map<String, dynamic>;
      final stops = service['stops'] as List;
      final fromIdx = _indexOfStation(stops, fromStationId);
      final toIdx = _indexOfStation(stops, toStationId);
      if (fromIdx < 0 || toIdx <= fromIdx) continue;

      final fromStop = stops[fromIdx] as Map<String, dynamic>;
      final toStop = stops[toIdx] as Map<String, dynamic>;
      final fromDayOffset = fromStop['dayOffset'] as int;
      final toDayOffset = toStop['dayOffset'] as int;

      final depart = _timeOn(
        day,
        fromStop['departureTime'] as String,
        fromDayOffset,
      );
      final arrive = _timeOn(day, toStop['arrivalTime'] as String, toDayOffset);

      journeys.add(
        Journey(
          from: from,
          to: to,
          train: _toTrain(service, trainsById),
          departureTime: depart,
          arrivalTime: arrive,
          price: null, // fares are not published in the public timetable
        ),
      );
    }

    journeys.sort((a, b) => a.departureTime.compareTo(b.departureTime));
    return journeys;
  }

  // -------------------------------------------------------------------------
  // Internal helpers
  // -------------------------------------------------------------------------

  Station _stationFromJson(Map<String, dynamic> s) {
    return Station(
      id: s['id'] as String,
      name: s['name'] as String,
      code: (s['code'] as String?) ?? '',
      city: (s['city'] as String?) ?? '',
      province: (s['province'] as String?) ?? '',
      facilities: const [],
    );
  }

  Map<String, Map<String, dynamic>> _trainsById(Map<String, dynamic> data) {
    return <String, Map<String, dynamic>>{
      for (final t in data['trains'] as List)
        (t as Map<String, dynamic>)['id'] as String: t,
    };
  }

  bool _stopAt(List stops, String stationId) {
    for (final s in stops) {
      if ((s as Map<String, dynamic>)['stationId'] == stationId) return true;
    }
    return false;
  }

  int _indexOfStation(List stops, String stationId) {
    for (var i = 0; i < stops.length; i++) {
      if ((stops[i] as Map<String, dynamic>)['stationId'] == stationId) {
        return i;
      }
    }
    return -1;
  }

  DateTime _timeOn(DateTime day, String hhmm, int dayOffset) {
    final parts = hhmm.split(':');
    return DateTime(
      day.year,
      day.month,
      day.day + dayOffset,
      int.parse(parts[0]),
      int.parse(parts[1]),
    );
  }

  Train _toTrain(
    Map<String, dynamic> service,
    Map<String, dynamic> trainsById,
  ) {
    final train = trainsById[service['trainId']] ?? service;
    final stops = [
      for (final s in service['stops'] as List)
        TrainStop(
          stationName: (s as Map<String, dynamic>)['stationName'] as String,
          arrivalTime: s['arrivalTime'] as String,
          departureTime: s['departureTime'] as String?,
          platform: s['platform'] as String?,
          delay: null,
          status: StopStatus.upcoming,
        ),
    ];
    return Train(
      id: service['id'] as String,
      name: train['name'] as String,
      number: service['number'] as String,
      status: 'Running',
      departureTime: service['departureTime'] as String,
      arrivalTime: service['arrivalTime'] as String,
      durationMin: service['durationMin'] as int?,
      type: _trainType(train['type'] as String),
      stops: stops,
    );
  }

  TrainType _trainType(String type) {
    switch (type) {
      case 'express':
        return TrainType.express;
      case 'passenger':
        return TrainType.regional;
      case 'shuttle':
        return TrainType.local;
      default:
        return TrainType.regional;
    }
  }
}
